// Generated by web/build.py from web/products.json. Do not edit by hand.
export const FILES = {
 "scorecard_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6a9ff102424c63.83360430_The_Weekly_Scorecard.pdf",
  "name": "The_Weekly_Scorecard.pdf"
 },
 "scorecard_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6a9ff10243fba9.35376520_The_Weekly_Scorecard.xlsx",
  "name": "The_Weekly_Scorecard.xlsx"
 },
 "husband_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1aa886.36523591_The_Godly_Husband_Field_Guide.pdf",
  "name": "The_Godly_Husband_Field_Guide.pdf"
 },
 "husband_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1b0a62266d2.09773419_The_Godly_Husband_Field_Guide_Tracker.xlsx",
  "name": "The_Godly_Husband_Field_Guide_Tracker.xlsx"
 },
 "marriage_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1dab38.01554037_The_Christian_Marriage_Workbook_for_Men.pdf",
  "name": "The_Christian_Marriage_Workbook_for_Men.pdf"
 },
 "devotional_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1aacf6.37012758_The_Husbands_Devotional_30_Mornings.pdf",
  "name": "The_Husbands_Devotional_30_Mornings.pdf"
 },
 "couples_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1f9a71.01645213_Christian_Couples_Conversation_Cards.pdf",
  "name": "Christian_Couples_Conversation_Cards.pdf"
 },
 "father_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1e6f23.62597105_The_Fathers_Field_Guide.pdf",
  "name": "The_Fathers_Field_Guide.pdf"
 },
 "father_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1b0a60dec52.94308288_The_Fathers_Field_Guide_Tracker.xlsx",
  "name": "The_Fathers_Field_Guide_Tracker.xlsx"
 },
 "fatherson_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b22c2a8.94257907_Father_and_Son_Conversation_Cards.pdf",
  "name": "Father_and_Son_Conversation_Cards.pdf"
 },
 "bible_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1d9164.57364847_The_Mens_Bible_Study_Eight_Weeks.pdf",
  "name": "The_Mens_Bible_Study_Eight_Weeks.pdf"
 },
 "disc_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1cdc32.19410002_The_Mens_Discipleship_Workbook.pdf",
  "name": "The_Mens_Discipleship_Workbook.pdf"
 },
 "disc_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1b0a623e867.40443129_The_Mens_Discipleship_Workbook_Tracker.xlsx",
  "name": "The_Mens_Discipleship_Workbook_Tracker.xlsx"
 },
 "prayer_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b2117a7.43700137_The_Prayer_Strategy_for_Men.pdf",
  "name": "The_Prayer_Strategy_for_Men.pdf"
 },
 "forty_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b2a48c1.74351572_Forty_Cards_for_Men.pdf",
  "name": "Forty_Cards_for_Men.pdf"
 },
 "step1_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6ab3bbee1bfe57.57860204_Step1-WhatTypeofManDoYouWanttoBe.pdf",
  "name": "Step1-WhatTypeofManDoYouWanttoBe.pdf"
 },
 "step2_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6ab3bbee0e6046.99310542_Step2-WhatAreYourGoals.pdf",
  "name": "Step2-WhatAreYourGoals.pdf"
 },
 "step3_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6ab3bbee186e72.20241185_Step3-WhatHasStoppedYouSoFar.pdf",
  "name": "Step3-WhatHasStoppedYouSoFar.pdf"
 },
 "step4_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6ab3bbee13eb81.59869416_Step4-TheLawsofaSystemThatHolds.pdf",
  "name": "Step4-TheLawsofaSystemThatHolds.pdf"
 },
 "step5_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6ab3bbee0cf5a6.77235838_Step5-TheFourPillars.pdf",
  "name": "Step5-TheFourPillars.pdf"
 },
 "step6_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6ab3bbee0e97b3.19602691_Step6-WhyYouNeedaSystem.pdf",
  "name": "Step6-WhyYouNeedaSystem.pdf"
 },
 "step7_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6ab3bbee13eb86.67921323_Step7-GodattheCenter.pdf",
  "name": "Step7-GodattheCenter.pdf"
 }
};
export const OFFERS = {
 "scorecard": {
  "plink": "plink_1UNzYUIJyHMhQ40v5Zv5UDtG",
  "files": [
   "scorecard_pdf",
   "scorecard_xlsx"
  ],
  "slug": "scorecard-lnxtejvx",
  "name": "The Weekly Scorecard"
 },
 "husband-guide": {
  "plink": "plink_1UNzYWIJyHMhQ40vXFIPyZpZ",
  "files": [
   "husband_pdf",
   "husband_xlsx"
  ],
  "slug": "husband-guide-coaukruz",
  "name": "The Godly Husband Field Guide"
 },
 "marriage-workbook": {
  "plink": "plink_1UNzYZIJyHMhQ40vqAW9bisH",
  "files": [
   "marriage_pdf"
  ],
  "slug": "marriage-workbook-ojd7cel2",
  "name": "The Christian Marriage Workbook for Men"
 },
 "devotional": {
  "plink": "plink_1UNzYbIJyHMhQ40vYTX9wQDd",
  "files": [
   "devotional_pdf"
  ],
  "slug": "devotional-uwfdnzsj",
  "name": "The Husband's Devotional: 30 Mornings"
 },
 "father-guide": {
  "plink": "plink_1UNzYdIJyHMhQ40vFdO92TJ5",
  "files": [
   "father_pdf",
   "father_xlsx"
  ],
  "slug": "father-guide-jnrvfbvb",
  "name": "The Father's Field Guide"
 },
 "father-son-cards": {
  "plink": "plink_1UNzYkIJyHMhQ40vfFvt2pwf",
  "files": [
   "fatherson_pdf"
  ],
  "slug": "father-son-cards-f2gken5w",
  "name": "Father and Son Conversation Cards"
 },
 "bible-study": {
  "plink": "plink_1UNzYsIJyHMhQ40vuXW1SFcZ",
  "files": [
   "bible_pdf"
  ],
  "slug": "bible-study-edzfbhfw",
  "name": "The Men's Bible Study: Eight Weeks"
 },
 "discipleship-workbook": {
  "plink": "plink_1UNzYuIJyHMhQ40v50j1mOnh",
  "files": [
   "disc_pdf",
   "disc_xlsx"
  ],
  "slug": "discipleship-workbook-3mxy3iuy",
  "name": "The Men's Discipleship Workbook"
 },
 "prayer-strategy": {
  "plink": "plink_1UNzYxIJyHMhQ40v1CmdNBu1",
  "files": [
   "prayer_pdf"
  ],
  "slug": "prayer-strategy-fyrdnigm",
  "name": "The Prayer Strategy for Men"
 },
 "forty-cards": {
  "plink": "plink_1UNzYzIJyHMhQ40vDfV43yT7",
  "files": [
   "forty_pdf"
  ],
  "slug": "forty-cards-geqjmizi",
  "name": "Forty Cards for Men"
 },
 "husband-kit": {
  "plink": "plink_1UNzZ7IJyHMhQ40v4R7xQq7M",
  "files": [
   "husband_pdf",
   "husband_xlsx",
   "marriage_pdf",
   "devotional_pdf",
   "couples_pdf"
  ],
  "slug": "husband-kit-soj4aqgs",
  "name": "The Husband Kit"
 },
 "father-kit": {
  "plink": "plink_1UNzajIJyHMhQ40v1aO61gpY",
  "files": [
   "father_pdf",
   "father_xlsx",
   "fatherson_pdf"
  ],
  "slug": "father-kit-1klcffxh",
  "name": "The Father Kit"
 },
 "faith-kit": {
  "plink": "plink_1UNzapIJyHMhQ40v6iCVcCIV",
  "files": [
   "bible_pdf",
   "disc_pdf",
   "disc_xlsx",
   "prayer_pdf"
  ],
  "slug": "faith-kit-dz9xsaqw",
  "name": "The Faith Kit"
 },
 "library": {
  "plink": "plink_1UNzb9IJyHMhQ40veB5olTGF",
  "files": [
   "scorecard_pdf",
   "scorecard_xlsx",
   "husband_pdf",
   "husband_xlsx",
   "marriage_pdf",
   "devotional_pdf",
   "couples_pdf",
   "father_pdf",
   "father_xlsx",
   "fatherson_pdf",
   "bible_pdf",
   "disc_pdf",
   "disc_xlsx",
   "prayer_pdf",
   "forty_pdf"
  ],
  "slug": "library-zjcdznwk",
  "name": "The Complete Be The Man Library"
 },
 "couples": {
  "plink": "plink_1UNzbHIJyHMhQ40vQv4YF1tj",
  "files": [],
  "slug": "couples-m7pwwkaj",
  "name": "Couples counseling: three sessions"
 }
};
export const CLUB = {
 "plinks": [
  "plink_1UOELMIJyHMhQ40viCMV3UFe",
  "plink_1UOELQIJyHMhQ40vIRTFPTbD"
 ],
 "prices": {
  "monthly": "price_1UOELDIJyHMhQ40vrMP26SAG",
  "yearly": "price_1UOELGIJyHMhQ40v3ZjwH3Qn"
 },
 "portal": "https://billing.stripe.com/p/login/3cIfZi17t31X0OPga06kg00",
 "mailerlite": {
  "members": "200754586620789990",
  "signin": "200754587357939123",
  "pairs": "200754588278589338"
 },
 "files": {
  "step1_pdf": 1,
  "step2_pdf": 1,
  "step3_pdf": 1,
  "step4_pdf": 1,
  "step5_pdf": 1,
  "step6_pdf": 1,
  "step7_pdf": 1,
  "scorecard_pdf": 1,
  "scorecard_xlsx": 1,
  "forty_pdf": 1,
  "devotional_pdf": 2,
  "couples_pdf": 2,
  "husband_pdf": 3,
  "husband_xlsx": 3,
  "father_pdf": 4,
  "father_xlsx": 4,
  "fatherson_pdf": 4,
  "marriage_pdf": 5,
  "prayer_pdf": 5,
  "bible_pdf": 6,
  "disc_pdf": 6,
  "disc_xlsx": 6
 },
 "lessons": {
  "month-2": 2,
  "month-3": 3,
  "month-4": 4,
  "month-5": 5,
  "month-6": 6
 }
};
