// Generated by web/build.py from web/products.json. Do not edit by hand.
export const FILES = {
 "scorecard_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6a9ff102424c63.83360430_The_Weekly_Scorecard.pdf",
  "name": "The_Weekly_Scorecard.pdf"
 },
 "scorecard_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6a9ff10243fba9.35376520_The_Weekly_Scorecard.xlsx",
  "name": "The_Weekly_Scorecard.xlsx"
 },
 "husband_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1aa886.36523591_The_Godly_Husband_Field_Guide.pdf",
  "name": "The_Godly_Husband_Field_Guide.pdf"
 },
 "husband_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1b0a62266d2.09773419_The_Godly_Husband_Field_Guide_Tracker.xlsx",
  "name": "The_Godly_Husband_Field_Guide_Tracker.xlsx"
 },
 "marriage_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1dab38.01554037_The_Christian_Marriage_Workbook_for_Men.pdf",
  "name": "The_Christian_Marriage_Workbook_for_Men.pdf"
 },
 "devotional_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1aacf6.37012758_The_Husbands_Devotional_30_Mornings.pdf",
  "name": "The_Husbands_Devotional_30_Mornings.pdf"
 },
 "couples_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1f9a71.01645213_Christian_Couples_Conversation_Cards.pdf",
  "name": "Christian_Couples_Conversation_Cards.pdf"
 },
 "father_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1e6f23.62597105_The_Fathers_Field_Guide.pdf",
  "name": "The_Fathers_Field_Guide.pdf"
 },
 "father_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1b0a60dec52.94308288_The_Fathers_Field_Guide_Tracker.xlsx",
  "name": "The_Fathers_Field_Guide_Tracker.xlsx"
 },
 "fatherson_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b22c2a8.94257907_Father_and_Son_Conversation_Cards.pdf",
  "name": "Father_and_Son_Conversation_Cards.pdf"
 },
 "bible_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1d9164.57364847_The_Mens_Bible_Study_Eight_Weeks.pdf",
  "name": "The_Mens_Bible_Study_Eight_Weeks.pdf"
 },
 "disc_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b1cdc32.19410002_The_Mens_Discipleship_Workbook.pdf",
  "name": "The_Mens_Discipleship_Workbook.pdf"
 },
 "disc_xlsx": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1b0a623e867.40443129_The_Mens_Discipleship_Workbook_Tracker.xlsx",
  "name": "The_Mens_Discipleship_Workbook_Tracker.xlsx"
 },
 "prayer_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b2117a7.43700137_The_Prayer_Strategy_for_Men.pdf",
  "name": "The_Prayer_Strategy_for_Men.pdf"
 },
 "forty_pdf": {
  "url": "https://d1yei2z3i6k35z.cloudfront.net/18912984/6aa1ab2b2a48c1.74351572_Forty_Cards_for_Men.pdf",
  "name": "Forty_Cards_for_Men.pdf"
 }
};
export const OFFERS = {
 "scorecard": {
  "plink": "plink_1UNzYUIJyHMhQ40v5Zv5UDtG",
  "files": [
   "scorecard_pdf",
   "scorecard_xlsx"
  ],
  "slug": "scorecard-lnxtejvx",
  "name": "The Weekly Scorecard"
 },
 "husband-guide": {
  "plink": "plink_1UNzYWIJyHMhQ40vXFIPyZpZ",
  "files": [
   "husband_pdf",
   "husband_xlsx"
  ],
  "slug": "husband-guide-coaukruz",
  "name": "The Godly Husband Field Guide"
 },
 "marriage-workbook": {
  "plink": "plink_1UNzYZIJyHMhQ40vqAW9bisH",
  "files": [
   "marriage_pdf"
  ],
  "slug": "marriage-workbook-ojd7cel2",
  "name": "The Christian Marriage Workbook for Men"
 },
 "devotional": {
  "plink": "plink_1UNzYbIJyHMhQ40vYTX9wQDd",
  "files": [
   "devotional_pdf"
  ],
  "slug": "devotional-uwfdnzsj",
  "name": "The Husband's Devotional: 30 Mornings"
 },
 "father-guide": {
  "plink": "plink_1UNzYdIJyHMhQ40vFdO92TJ5",
  "files": [
   "father_pdf",
   "father_xlsx"
  ],
  "slug": "father-guide-jnrvfbvb",
  "name": "The Father's Field Guide"
 },
 "father-son-cards": {
  "plink": "plink_1UNzYkIJyHMhQ40vfFvt2pwf",
  "files": [
   "fatherson_pdf"
  ],
  "slug": "father-son-cards-f2gken5w",
  "name": "Father and Son Conversation Cards"
 },
 "bible-study": {
  "plink": "plink_1UNzYsIJyHMhQ40vuXW1SFcZ",
  "files": [
   "bible_pdf"
  ],
  "slug": "bible-study-edzfbhfw",
  "name": "The Men's Bible Study: Eight Weeks"
 },
 "discipleship-workbook": {
  "plink": "plink_1UNzYuIJyHMhQ40v50j1mOnh",
  "files": [
   "disc_pdf",
   "disc_xlsx"
  ],
  "slug": "discipleship-workbook-3mxy3iuy",
  "name": "The Men's Discipleship Workbook"
 },
 "prayer-strategy": {
  "plink": "plink_1UNzYxIJyHMhQ40v1CmdNBu1",
  "files": [
   "prayer_pdf"
  ],
  "slug": "prayer-strategy-fyrdnigm",
  "name": "The Prayer Strategy for Men"
 },
 "forty-cards": {
  "plink": "plink_1UNzYzIJyHMhQ40vDfV43yT7",
  "files": [
   "forty_pdf"
  ],
  "slug": "forty-cards-geqjmizi",
  "name": "Forty Cards for Men"
 },
 "husband-kit": {
  "plink": "plink_1UNzZ7IJyHMhQ40v4R7xQq7M",
  "files": [
   "husband_pdf",
   "husband_xlsx",
   "marriage_pdf",
   "devotional_pdf",
   "couples_pdf"
  ],
  "slug": "husband-kit-soj4aqgs",
  "name": "The Husband Kit"
 },
 "father-kit": {
  "plink": "plink_1UNzajIJyHMhQ40v1aO61gpY",
  "files": [
   "father_pdf",
   "father_xlsx",
   "fatherson_pdf"
  ],
  "slug": "father-kit-1klcffxh",
  "name": "The Father Kit"
 },
 "faith-kit": {
  "plink": "plink_1UNzapIJyHMhQ40v6iCVcCIV",
  "files": [
   "bible_pdf",
   "disc_pdf",
   "disc_xlsx",
   "prayer_pdf"
  ],
  "slug": "faith-kit-dz9xsaqw",
  "name": "The Faith Kit"
 },
 "library": {
  "plink": "plink_1UNzb9IJyHMhQ40veB5olTGF",
  "files": [
   "scorecard_pdf",
   "scorecard_xlsx",
   "husband_pdf",
   "husband_xlsx",
   "marriage_pdf",
   "devotional_pdf",
   "couples_pdf",
   "father_pdf",
   "father_xlsx",
   "fatherson_pdf",
   "bible_pdf",
   "disc_pdf",
   "disc_xlsx",
   "prayer_pdf",
   "forty_pdf"
  ],
  "slug": "library-zjcdznwk",
  "name": "The Complete Be The Man Library"
 },
 "couples": {
  "plink": "plink_1UNzbHIJyHMhQ40vQv4YF1tj",
  "files": [],
  "slug": "couples-m7pwwkaj",
  "name": "Couples counseling: three sessions"
 }
};
